name: Daily lessons
on:
  schedule:
    - cron: '0 19 * * 1' # <- Use UTC Time +0 , change your time here ( 14 is hour , 0 is minutes ) and use 24-hour format
    - cron: '0 7 * * 0,2,3,4,5,6'
   
jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Run DuoXPy
        run: python main.py
        env:
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          LESSONS: 10
